""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable features not Vi compatible
set nocompatible

" Initialize pathogen
execute pathogen#infect()
execute pathogen#helptags()

filetype plugin on
filetype indent on

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VIM user interface
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Show current position
set ruler

" Show line numbers
set number

" Show current editing mode
set showmode

" Show matching brackets when text indicator is over them
set showmatch

" Show the status line
set laststatus=2

" Always display the tabline, even if there is only one tab
set showtabline=2 

" Colored column
highlight ColorColumn ctermbg=blue
set colorcolumn=81

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Colors and Fonts
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
syntax on
set background=dark

" Enable 256 colors in Vim
set t_Co=256

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Text, tab and indent related
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" File type specific options overwrite these parameters (see .vim/after/ftplugin)
" Use tabs with 4 spaces width
set noexpandtab
set shiftwidth=4
set tabstop=4

" Indentation
set autoindent
set smartindent
set shiftround

" Smart backspace
set backspace=indent,eol,start

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Search 
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Highlight search results
set hlsearch

" Ctrl-N stops hlsearch 
nmap <silent> <C-N> :silent noh<cr>

set ignorecase

" First search for the current directory containing the current
" file, then the current directory, then each directory under
" the current directory
set path=.,,**

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Files, backups and undo
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Turn backup off
set nobackup
set nowb
set noswapfile

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Editing mappings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = "\<Space>"
let g:mapleader = "\<Space>"

" Fast saving
nmap <leader>w :w<cr>

" Fast quitting
nmap <leader>q :q<cr>

" Remap VIM 0 to first non-blank character
map 0 ^

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugins
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" ctrlP config
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'a'

" Tabularize shortcuts
nnoremap <Leader>a :Tabularize /
vnoremap <Leader>a :Tabularize /

" Enable expansion with delimitMate
let g:delimitMate_expand_cr = 1

" Syntastic config
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1

" Vim-Tex
let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_compiler_latexmk = {'callback' : 0}

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Misc
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
	\ if line("'\"") > 0 && line("'\"") <= line("$") |
	\ exe "normal! g`\"" |
	\ endif
" Remember info about open buffers on close
set viminfo^=%

" Disable automatic comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
