#!/bin/bash

# More info: https://wiki.archlinux.org/index.php/Full_system_backup_with_rsync
sudo rsync  -aAX --info=progress2 --delete --exclude={"/home/*/.thumbnails/*","/home/*/.cache/mozilla/*","/home/*/.cache/chromium/*","/home/*/.local/share/Trash/*","/home/*/.gvfs"} /home/haltode/ /media/haltode/usb_backup/laptop
